
import React, { useState } from 'react';

interface InstallationWizardProps {
  onComplete: () => void;
}

export const InstallationWizard: React.FC<InstallationWizardProps> = ({ onComplete }) => {
  const [step, setStep] = useState(1);
  const [config, setConfig] = useState({
    supabaseUrl: '',
    supabaseKey: '',
    vercelProject: '',
    operatorName: ''
  });

  const sqlSchema = `
-- 1. Create Leads Table
CREATE TABLE leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid TEXT UNIQUE NOT NULL,
  name TEXT,
  email TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  notes TEXT,
  tags TEXT[] DEFAULT '{}'
);

-- 2. Create Messages Table
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL,
  sender_id TEXT NOT NULL,
  sender_type TEXT NOT NULL, -- 'client' or 'operator'
  message_text TEXT NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable Realtime
alter publication supabase_realtime add table messages;
alter publication supabase_realtime add table leads;

-- 4. Set RLS Policies
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert" ON leads FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select" ON leads FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select" ON messages FOR SELECT USING (true);
  `.trim();

  const handleNext = () => setStep(step + 1);
  const handleBack = () => setStep(step - 1);

  const saveConfig = () => {
    localStorage.setItem('flourish_config', JSON.stringify(config));
    localStorage.setItem('flourish_installed', 'true');
    onComplete();
  };

  return (
    <div className="min-h-screen bg-slate-900 flex items-center justify-center p-6 font-['Plus_Jakarta_Sans']">
      <div className="max-w-4xl w-full bg-white rounded-[3rem] shadow-2xl overflow-hidden flex flex-col md:flex-row min-h-[600px]">
        {/* Sidebar Progress */}
        <div className="w-full md:w-80 bg-slate-900 p-10 text-white flex flex-col justify-between border-r border-white/5">
          <div>
            <div className="w-12 h-12 bg-indigo-600 rounded-2xl flex items-center justify-center text-white font-black text-xl mb-8">F</div>
            <h2 className="text-2xl font-black uppercase tracking-tighter mb-8 leading-tight">Vercel Deployment</h2>
            
            <div className="space-y-6">
              {[
                { id: 1, label: 'Environment' },
                { id: 2, label: 'Supabase API' },
                { id: 3, label: 'Database SQL' },
                { id: 4, label: 'Google AI Studio' },
                { id: 5, label: 'Vercel Push' },
                { id: 6, label: 'Finalize' }
              ].map((s) => (
                <div key={s.id} className="flex items-center gap-4">
                  <div className={`w-8 h-8 rounded-full border-2 flex items-center justify-center text-[10px] font-black transition-all ${
                    step === s.id ? 'bg-indigo-600 text-white border-indigo-600' : 
                    step > s.id ? 'bg-emerald-500 border-emerald-500 text-white' : 'border-white/20 text-white/20'
                  }`}>
                    {step > s.id ? '✓' : s.id}
                  </div>
                  <span className={`text-[10px] font-black uppercase tracking-widest ${step >= s.id ? 'text-white' : 'text-white/20'}`}>
                    {s.label}
                  </span>
                </div>
              ))}
            </div>
          </div>
          <p className="text-[10px] text-white/40 font-bold uppercase tracking-widest">v2.1.0 • Supabase + Vercel</p>
        </div>

        {/* Content Area */}
        <div className="flex-1 p-10 md:p-16 flex flex-col justify-center relative">
          {step === 1 && (
            <div className="animate-in fade-in slide-in-from-right-4 duration-500">
              <h3 className="text-3xl font-black text-slate-900 mb-4 uppercase tracking-tighter">New Ecosystem</h3>
              <p className="text-slate-500 mb-8 leading-relaxed">Let's connect your frontend to Vercel and your data to Supabase. This creates a high-performance, edge-first chat platform.</p>
              <div className="space-y-4">
                <input 
                  type="text" 
                  placeholder="Platform Identifier (e.g. Flourish Pro)"
                  className="w-full p-4 bg-slate-50 rounded-2xl border-2 border-transparent focus:border-indigo-600 outline-none font-bold text-sm"
                  value={config.operatorName}
                  onChange={(e) => setConfig({...config, operatorName: e.target.value})}
                />
              </div>
              <button onClick={handleNext} className="mt-10 px-10 py-4 bg-slate-900 text-white rounded-2xl font-black text-xs uppercase tracking-widest shadow-xl shadow-slate-200">Start Migration</button>
            </div>
          )}

          {step === 2 && (
            <div className="animate-in fade-in slide-in-from-right-4 duration-500">
              <h3 className="text-3xl font-black text-slate-900 mb-4 uppercase tracking-tighter">Supabase Backend</h3>
              <p className="text-slate-500 mb-8 text-sm">Retrieve these from <strong>Project Settings > API</strong> in your Supabase dashboard.</p>
              <div className="space-y-4">
                <input 
                  type="text" 
                  placeholder="SUPABASE_URL"
                  className="w-full p-4 bg-slate-50 rounded-2xl border-2 border-transparent focus:border-indigo-600 outline-none font-medium text-sm"
                  value={config.supabaseUrl}
                  onChange={(e) => setConfig({...config, supabaseUrl: e.target.value})}
                />
                <input 
                  type="password" 
                  placeholder="SUPABASE_ANON_KEY"
                  className="w-full p-4 bg-slate-50 rounded-2xl border-2 border-transparent focus:border-indigo-600 outline-none font-medium text-sm"
                  value={config.supabaseKey}
                  onChange={(e) => setConfig({...config, supabaseKey: e.target.value})}
                />
              </div>
              <div className="flex gap-4 mt-10">
                <button onClick={handleBack} className="px-8 py-4 bg-slate-100 text-slate-500 rounded-2xl font-black text-xs uppercase tracking-widest">Back</button>
                <button onClick={handleNext} className="flex-1 py-4 bg-indigo-600 text-white rounded-2xl font-black text-xs uppercase tracking-widest shadow-xl shadow-indigo-100">Connect Data</button>
              </div>
            </div>
          )}

          {step === 3 && (
            <div className="animate-in fade-in slide-in-from-right-4 duration-500">
              <h3 className="text-3xl font-black text-slate-900 mb-4 uppercase tracking-tighter">SQL Provisioning</h3>
              <p className="text-slate-500 mb-6 text-sm">Run this in your Supabase <strong>SQL Editor</strong> to create the tables for Leads and Messages.</p>
              <div className="relative">
                <pre className="bg-slate-900 text-indigo-300 p-6 rounded-2xl text-[10px] h-48 overflow-y-auto font-mono">
                  {sqlSchema}
                </pre>
                <button 
                  onClick={() => navigator.clipboard.writeText(sqlSchema)}
                  className="absolute top-4 right-4 bg-white/10 text-white px-2 py-1 rounded text-[8px] font-bold uppercase"
                >
                  Copy SQL
                </button>
              </div>
              <div className="flex gap-4 mt-10">
                <button onClick={handleBack} className="px-8 py-4 bg-slate-100 text-slate-500 rounded-2xl font-black text-xs uppercase tracking-widest">Back</button>
                <button onClick={handleNext} className="flex-1 py-4 bg-indigo-600 text-white rounded-2xl font-black text-xs uppercase tracking-widest shadow-xl shadow-indigo-100">Schema Ready</button>
              </div>
            </div>
          )}

          {step === 4 && (
            <div className="animate-in fade-in slide-in-from-right-4 duration-500">
              <h3 className="text-3xl font-black text-slate-900 mb-4 uppercase tracking-tighter">Google AI Studio</h3>
              <p className="text-slate-500 mb-8 text-sm">Flourish uses Gemini for Smart Replies. Get your API Key from <a href="https://aistudio.google.com/" target="_blank" className="text-indigo-600 font-bold underline">AI Studio</a>.</p>
              <div className="p-6 bg-indigo-50 border border-indigo-100 rounded-2xl mb-8">
                 <h4 className="text-[10px] font-black uppercase tracking-widest text-indigo-600 mb-2">Vercel Setup Tip</h4>
                 <p className="text-[11px] text-indigo-700 font-medium">Add <code>API_KEY</code> to your Vercel Environment Variables to enable AI in production.</p>
              </div>
              <div className="flex gap-4 mt-10">
                <button onClick={handleBack} className="px-8 py-4 bg-slate-100 text-slate-500 rounded-2xl font-black text-xs uppercase tracking-widest">Back</button>
                <button onClick={handleNext} className="flex-1 py-4 bg-indigo-600 text-white rounded-2xl font-black text-xs uppercase tracking-widest shadow-xl shadow-indigo-100">AI Key Ready</button>
              </div>
            </div>
          )}

          {step === 5 && (
            <div className="animate-in fade-in slide-in-from-right-4 duration-500">
              <h3 className="text-3xl font-black text-slate-900 mb-4 uppercase tracking-tighter">Deploy to Vercel</h3>
              <p className="text-slate-500 mb-8 text-sm">Sync your project with Vercel for automatic scaling and global availability.</p>
              <div className="space-y-4">
                 <div className="flex gap-4 p-4 bg-slate-50 rounded-xl">
                    <div className="w-8 h-8 bg-black rounded-full flex items-center justify-center text-white text-[10px] font-black">1</div>
                    <p className="text-xs font-medium text-slate-700">Push your code to <strong>GitHub</strong> or <strong>GitLab</strong>.</p>
                 </div>
                 <div className="flex gap-4 p-4 bg-slate-50 rounded-xl">
                    <div className="w-8 h-8 bg-black rounded-full flex items-center justify-center text-white text-[10px] font-black">2</div>
                    <p className="text-xs font-medium text-slate-700">Import the repo in <strong>Vercel Dashboard</strong>.</p>
                 </div>
                 <div className="flex gap-4 p-4 bg-slate-50 rounded-xl">
                    <div className="w-8 h-8 bg-black rounded-full flex items-center justify-center text-white text-[10px] font-black">3</div>
                    <p className="text-xs font-medium text-slate-700">Add Supabase keys as <strong>Environment Variables</strong>.</p>
                 </div>
              </div>
              <div className="flex gap-4 mt-10">
                <button onClick={handleBack} className="px-8 py-4 bg-slate-100 text-slate-500 rounded-2xl font-black text-xs uppercase tracking-widest">Back</button>
                <button onClick={handleNext} className="flex-1 py-4 bg-indigo-600 text-white rounded-2xl font-black text-xs uppercase tracking-widest shadow-xl shadow-indigo-100">I've Deployed</button>
              </div>
            </div>
          )}

          {step === 6 && (
            <div className="text-center animate-in zoom-in-95 duration-500">
              <div className="w-24 h-24 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-8">
                <svg className="w-12 h-12" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <h3 className="text-3xl font-black text-slate-900 mb-2 uppercase tracking-tighter">System Live</h3>
              <p className="text-slate-500 mb-10 text-sm leading-relaxed">Your Vercel deployment is synchronized with Supabase. You are ready to handle real client traffic.</p>
              
              <button onClick={saveConfig} className="w-full py-5 bg-indigo-600 text-white rounded-3xl font-black text-sm uppercase tracking-[0.2em] shadow-2xl shadow-indigo-200 transition-all hover:scale-105 active:scale-95">
                Launch Command Center
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
